name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '7.6.2'
          projectPath: 'C:\Users\karim\Katalon Studio\My First Web UI Project\My First Web UI Project.prj' 
          args: 'noSplash -retry=0 -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey = "5ba2f3e8-6780-441d-b20c-b438b8a1a14e" --config -webui.autoUpdateDrivers=true'
